allowBuilds:
  msw: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 10080

trustPolicy: no-downgrade

trustPolicyExclude:
  - 'eslint-import-resolver-typescript@3.10.1'
  - 'semver@6.3.1'
